[project]
name = "revil"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pwntools>=4.14.1",
]

[project.scripts]
revil = "revil.revil:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
